### ISSUE TITLE
Publish to MELPA?

### ISSUE THREAD

**Issue by jinnovation** [jethrokuan/filenotify-recursive#2]
Hey @jethrokuan,

I'd love to use this package for my own budding package (jinnovation/kele.el#43) as I've run head-on into the need for recursive file-watching. Any chance I could convince you to publish this to MELPA?

**Comment by jinnovation** [comment]
Ah, I see that I'm late to the party: melpa/melpa#7694

**Comment by jethrokuan** [comment]
yeah i haven't had the time to work on these things anymore, but feel free to fork/adapt it for your usecase

**Comment by jinnovation** [comment]
Sounds good and make sense. Feel free to close this then 👍
